### ISSUE TITLE
Document mercury localnet 

### ISSUE THREAD

**Issue by divyakoshy** [renproject/mercury#25]
Mercury localnet deployment is currently undocumented and requires the need to build multiple dockerfiles before being able to start up localnet. This process can be simplified and automated.

## Tracking

- [ ] Automate mercury localnet deployment
- [ ] Document localnet mercury deployment process
- [ ] Automate deployment of ethereum along with relevant `darknode-sol` contracts

**Comment by loongy** [comment]
New lotan changes make this issue irrelevant.
